export const sampleLedgerData = [
  {
    Category: "CLEANING",
    Amount: 5508,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name: "Janitorial services for Building (not Premises)",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 153,
      y0: 375.95,
      x1: 543,
      y1: 403.03,
    },
  },
  {
    Category: "INSURANCE",
    Amount: 13578.75,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name: "Insurance carried by Landlord",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 153,
      y0: 155.15,
      x1: 543.01,
      y1: 196.03,
    },
  },
  {
    Category: "MANAGEMENT FEES",
    Amount: 28760.9,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name: "Management fees",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 153,
      y0: 210.35,
      x1: 543,
      y1: 251.23,
    },
  },
  {
    Category: "REPAIRS AND MAINTENANCE",
    Amount: 38051.31,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name:
      "Repairs and maintenance of Building, Land and Common Areas",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 153,
      y0: 237.95,
      x1: 543.01,
      y1: 320.23,
    },
  },
  {
    Category: "GROUNDS MAINTENANCE",
    Amount: 10388,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name:
      "Repairs and maintenance of Building, Land and Common Areas",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 153,
      y0: 237.95,
      x1: 543.01,
      y1: 320.23,
    },
  },
  {
    Category: "REAL ESTATE TAXES",
    Amount: 48134.43,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name: "Real Estate Taxes",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 246.12,
      y0: 155.15,
      x1: 502.9,
      y1: 168.43,
    },
  },
  {
    Category: "UTILITIES",
    Amount: 82735.26,
    "Included in Cap": true,
    "Lease Page": 6,
    lease_clause_name: "Utility services",
    clause_pdfCoordinates: {
      page: 6,
      page_width: 612,
      page_height: 792,
      x0: 153,
      y0: 389.75,
      x1: 543.01,
      y1: 416.83,
    },
  },
  {
    Category: "ADMINISTRATIVE",
    Amount: 11131.89,
    "Included in Cap": true,
    "Lease Page": 0,
    lease_clause_name: "",
    clause_pdfCoordinates: null,
  },
];

export const sampleMetricsData = [
  {
    Metric: "CAM Pro-Rata (%)",
    Value: 36.06,
  },
  {
    Metric: "TAX Pro-Rata (%)",
    Value: 100,
  },
  {
    Metric: "INSURANCE Pro-Rata (%)",
    Value: 100,
  },
  {
    Metric: "Cap on CAM (%)",
    Value: 5,
  },
  {
    Metric: "Previous Year Capped CAM Total",
    Value: 214459.686,
  },
  {
    Metric: "TAX Total Expense",
    Value: 0,
  },
  {
    Metric: "INSURANCE Total Expense",
    Value: 0,
  },
  {
    Metric: "CAM Prior Billed",
    Value: -70782.72,
  },
  {
    Metric: "TAX Prior Billed",
    Value: 0,
  },
  {
    Metric: "INSURANCE Prior Billed",
    Value: 0,
  },
  {
    Metric: "CAM Stated Balance Due",
    Value: 11978.16,
  },
  {
    Metric: "TAX Stated Balance Due",
    Value: 0,
  },
  {
    Metric: "INSURANCE Stated Balance Due",
    Value: 0,
  },
  {
    Metric: "Base Year",
    Value: 2024,
  },
  {
    Metric: "Base Year Total",
    Value: 5003,
  },
];

export const sampleResultsData = [
  {
    Type: "Line Item",
    Description: "Utilities",
    "Current Yr Charge": 5243.21,
    "Prior Yr Amount": 4718.89,
    "Cap Value": 4920.16,
    Variance: 323.05,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 1149.72,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Maintenance Salaries",
    "Current Yr Charge": 0,
    "Prior Yr Amount": 0,
    "Cap Value": 0,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Management Fees",
    "Current Yr Charge": 10924.03,
    "Prior Yr Amount": 9831.63,
    "Cap Value": 10250.97,
    Variance: 673.06,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 2395.39,
    "Lease Page": 6,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Maintenance & Repairs",
    "Current Yr Charge": 19710.49,
    "Prior Yr Amount": 17739.44,
    "Cap Value": 18496.06,
    Variance: 1214.43,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 4322.07,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Materials & Supplies",
    "Current Yr Charge": 0,
    "Prior Yr Amount": 0,
    "Cap Value": 0,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Truck & Equipment Expense",
    "Current Yr Charge": 0,
    "Prior Yr Amount": 0,
    "Cap Value": 0,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Landscaping & Grounds",
    "Current Yr Charge": 8008.74,
    "Prior Yr Amount": 7207.87,
    "Cap Value": 7515.3,
    Variance: 493.44,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 1756.14,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Communications",
    "Current Yr Charge": 0,
    "Prior Yr Amount": 0,
    "Cap Value": 0,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Lease Page": 0,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Trash Removal",
    "Current Yr Charge": 10638.12,
    "Prior Yr Amount": 9574.31,
    "Cap Value": 9982.67,
    Variance: 655.45,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 2332.7,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Miscellaneous",
    "Current Yr Charge": 0,
    "Prior Yr Amount": 0,
    "Cap Value": 0,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Lease Page": 0,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Security",
    "Current Yr Charge": 0,
    "Prior Yr Amount": 0,
    "Cap Value": 0,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Lease Page": 0,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Administrative Fee 10% (Capped)",
    "Current Yr Charge": 5452.46,
    "Prior Yr Amount": 4907.21,
    "Cap Value": 5116.52,
    Variance: 335.94,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 1195.6,
    "Lease Page": 6,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Snow Removal",
    "Current Yr Charge": 13000,
    "Prior Yr Amount": 11700,
    "Cap Value": 12199.03,
    Variance: 800.97,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 2850.61,
    "Lease Page": 5,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Line Item",
    Description: "Administrative Fee 10% (Non-Capped)",
    "Current Yr Charge": 1300,
    "Prior Yr Amount": 1170,
    "Cap Value": 1219.9,
    Variance: 80.1,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 285.06,
    "Lease Page": 6,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "",
    Description: "",
    "Current Yr Charge": null,
    "Prior Yr Amount": null,
    "Cap Value": null,
    Variance: null,
    "Pro-Rata (%)": null,
    "Tenant Share": null,
    "Lease Page": null,
    clause_pdfCoordinates: null,
    Status: null,
    "Reviewer Comment": "",
  },
  {
    Type: "Consolidated Summary",
    Description: "CAM - TOTAL",
    "Current Yr Charge": 74277.05,
    "Prior Yr Amount": null,
    "Cap Value": 69700.6,
    Variance: 2551.44,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 16287.29,
    "Lease Page": null,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
  {
    Type: "Consolidated Summary",
    Description: "TAX",
    "Current Yr Charge": 30887.92,
    "Prior Yr Amount": null,
    "Cap Value": 30887.92,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 7217.73,
    "Lease Page": null,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Consolidated Summary",
    Description: "INSURANCE",
    "Current Yr Charge": 3623.82,
    "Prior Yr Amount": null,
    "Cap Value": 3623.82,
    Variance: 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 846.8,
    "Lease Page": null,
    clause_pdfCoordinates: null,
    Status: "pass",
    "Reviewer Comment": "",
  },
  {
    Type: "Consolidated Summary",
    Description: "GRAND TOTAL",
    "Current Yr Charge": 108788.79,
    "Prior Yr Amount": null,
    "Cap Value": 104212.34,
    Variance: 2551.44,
    "Pro-Rata (%)": null,
    "Tenant Share": 24351.82,
    "Lease Page": null,
    clause_pdfCoordinates: null,
    Status: "fail",
    "Reviewer Comment": "",
  },
];

export const sampleConsolidatedReconciliationData = [
  {
    Category: "CAM - Capped",
    "Actual Property Exp.": 74277.06,
    "Recoverable Exp. (Allowed)": 69700.6,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 16287.29,
    "Prior Billed (Escrow)": null,
    "Calculated Balance": null,
    "Stated Balance Due": null,
    Variance: null,
  },
  {
    Category: "CAM - Uncapped",
    "Actual Property Exp.": 0,
    "Recoverable Exp. (Allowed)": 0,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 0,
    "Prior Billed (Escrow)": null,
    "Calculated Balance": null,
    "Stated Balance Due": null,
    Variance: null,
  },
  {
    Category: "CAM - TOTAL",
    "Actual Property Exp.": 74277.06,
    "Recoverable Exp. (Allowed)": 69700.6,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 16287.29,
    "Prior Billed (Escrow)": 12573,
    "Calculated Balance": 3714.29,
    "Stated Balance Due": 1162.85,
    Variance: 2551.44,
  },
  {
    Category: "TAX",
    "Actual Property Exp.": 30887.92,
    "Recoverable Exp. (Allowed)": 30887.92,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 7217.73,
    "Prior Billed (Escrow)": 7030.92,
    "Calculated Balance": 186.81,
    "Stated Balance Due": 186.81,
    Variance: 0,
  },
  {
    Category: "INSURANCE",
    "Actual Property Exp.": 3623.82,
    "Recoverable Exp. (Allowed)": 3623.82,
    "Pro-Rata (%)": 23.3675,
    "Tenant Share": 846.8,
    "Prior Billed (Escrow)": 1385.04,
    "Calculated Balance": -538.24,
    "Stated Balance Due": -538.24,
    Variance: 0,
  },
  {
    Category: "",
    "Actual Property Exp.": 108788.8,
    "Recoverable Exp. (Allowed)": 104212.34,
    "Pro-Rata (%)": null,
    "Tenant Share": 24351.82,
    "Prior Billed (Escrow)": 20988.96,
    "Calculated Balance": 3362.86,
    "Stated Balance Due": 811.42,
    Variance: 2551.44,
  },
];
